@hostname = localhost
@port = 8080
@host = {{hostname}}:{{port}}
@contentType = application/json
@createdAt = {{$datetime iso8601}}
@modifiedBy = {{$processEnv USERNAME}}

###

@name = amit

###
GET http://{{host}}/api/v1/status HTTP/1.1

###
GET http://{{host}}/api/v1/hello HTTP/1.1

###
GET http://{{host}}/api/v1/ping HTTP/1.1

###

POST http://{{host}}/api/v1/author/{{name}} HTTP/1.1
Content-Type: {{contentType}}

{
    "content": "foo bar",
    "created_at": "{{createdAt}}",
    "modified_by": "{{modifiedBy}}",
    "additional_info" : "some extra details"
}

### /opening endpoints
POST http://{{host}}/api/v1/opening HTTP/1.1
Content-Type: {{contentType}}

{
    "title": "{{name}}'s Position",
    "description": "Job opening for {{name}}",
    "location": "Remote",
    "salary": 100000,
    "created_at": "{{createdAt}}",
    "modified_by": "{{modifiedBy}}"
}

### /opening endpoints
POST http://{{host}}/api/v1/opening HTTP/1.1
Content-Type: {{contentType}}

{
    "role": "Software Engineer"
}

### list openings
GET http://{{host}}/api/v1/openings HTTP/1.1
Content-Type: {{contentType}}

### show opening
GET http://{{host}}/api/v1/opening/1 HTTP/1.1
Content-Type: {{contentType}}